import type { Account, AlertRule, BuyPlan, Holding, Settings } from "./types";

export const defaultAccounts: Account[] = [
  {
    id: "acct-brokerage",
    name: "한국투자증권 위탁계좌",
    brokerage: "한국투자증권",
    accountType: "위탁",
    role: "적극투자",
    cashAmount: 3000000,
    memo: "삼성전자, SK하이닉스, 반도체 ETF와 소액 스윙 실험 관리",
  },
  {
    id: "acct-isa",
    name: "한국투자증권 ISA",
    brokerage: "한국투자증권",
    accountType: "ISA",
    role: "절세형 ETF",
    cashAmount: 5000000,
    memo: "국내상장 미국 ETF 정기매수",
  },
  {
    id: "acct-pension",
    name: "한국투자증권 연금계좌",
    brokerage: "한국투자증권",
    accountType: "연금",
    role: "장기연금",
    cashAmount: 2000000,
    memo: "단기 매매 금지. 은퇴자산 중심",
  },
  {
    id: "acct-cma",
    name: "한국투자증권 CMA",
    brokerage: "한국투자증권",
    accountType: "CMA",
    role: "방어현금",
    cashAmount: 10000000,
    memo: "조정장 대기자금. 기본적으로 투자 가능 금액에서 제외",
  },
];

export const defaultHoldings: Holding[] = [
  {
    id: "holding-samsung",
    accountId: "acct-brokerage",
    brokerage: "한국투자증권",
    accountName: "한국투자증권 위탁계좌",
    accountType: "위탁",
    symbol: "005930",
    name: "삼성전자",
    assetClass: "반도체",
    quantity: 100,
    avgPrice: 75000,
    currentPrice: 78000,
    targetWeight: 20,
    memo: "100만 원 단위 눌림 매수 검토",
    high1m: 82000,
    high3m: 85000,
    high6m: 88000,
    ma20: 79000,
    ma60: 76000,
    dayChangeRate: -0.8,
  },
  {
    id: "holding-hynix",
    accountId: "acct-brokerage",
    brokerage: "한국투자증권",
    accountName: "한국투자증권 위탁계좌",
    accountType: "위탁",
    symbol: "000660",
    name: "SK하이닉스",
    assetClass: "반도체",
    quantity: 20,
    avgPrice: 210000,
    currentPrice: 225000,
    targetWeight: 25,
    memo: "1주 단위 매수 판단",
    high1m: 236000,
    high3m: 245000,
    high6m: 248000,
    ma20: 228000,
    ma60: 216000,
    dayChangeRate: -1.2,
  },
  {
    id: "holding-kodex-chip",
    accountId: "acct-brokerage",
    brokerage: "한국투자증권",
    accountName: "한국투자증권 위탁계좌",
    accountType: "위탁",
    symbol: "446770",
    name: "KODEX 삼성전자SK하이닉스",
    assetClass: "반도체",
    quantity: 300,
    avgPrice: 11500,
    currentPrice: 12100,
    targetWeight: 10,
    memo: "100만 원 단위 매수 검토",
    high1m: 12600,
    high3m: 13200,
    high6m: 13600,
    ma20: 12200,
    ma60: 11800,
    dayChangeRate: -0.5,
  },
  {
    id: "holding-sp500",
    accountId: "acct-isa",
    brokerage: "한국투자증권",
    accountName: "한국투자증권 ISA",
    accountType: "ISA",
    symbol: "360750",
    name: "TIGER 미국S&P500",
    assetClass: "미국ETF",
    quantity: 250,
    avgPrice: 18800,
    currentPrice: 19600,
    targetWeight: 24,
    memo: "정기매수 60%",
    high1m: 19900,
    high3m: 20500,
    high6m: 20800,
    ma20: 19400,
    ma60: 18850,
    dayChangeRate: -1.4,
  },
  {
    id: "holding-nasdaq",
    accountId: "acct-isa",
    brokerage: "한국투자증권",
    accountName: "한국투자증권 ISA",
    accountType: "ISA",
    symbol: "133690",
    name: "TIGER 미국나스닥100",
    assetClass: "미국ETF",
    quantity: 150,
    avgPrice: 118000,
    currentPrice: 122000,
    targetWeight: 16,
    memo: "정기매수 40%",
    high1m: 125000,
    high3m: 131000,
    high6m: 134000,
    ma20: 121000,
    ma60: 116000,
    dayChangeRate: -2.1,
  },
];

export const defaultSettings: Settings = {
  totalCapital: 50000000,
  defensiveCashTargetType: "percentage",
  defensiveCashTargetValue: 20,
  semiconductorMaxWeight: 60,
  usEtfTargetWeight: 38,
  swingMaxWeight: 5,
  yearlyTargetRate: 114,
  monthlyBuyAmount: 1000000,
  sp500BuyRatio: 60,
  nasdaqBuyRatio: 40,
  cmaMinimumCash: 8000000,
};

export const defaultBuyPlan: BuyPlan = {
  mode: "2회 분할",
  nextBuyDate: new Date().toISOString().slice(0, 10),
  customInstallments: 4,
  completedFirst: false,
  completedSecond: false,
};

export const defaultAlertRules: AlertRule[] = [
  { id: "alert-hynix-5", symbol: "000660", name: "SK하이닉스", ruleType: "3개월 고점 대비 하락률", thresholdValue: -5, actionMessage: "눌림 후보 알림", enabled: true, severity: "info" },
  { id: "alert-hynix-8", symbol: "000660", name: "SK하이닉스", ruleType: "3개월 고점 대비 하락률", thresholdValue: -8, actionMessage: "1차 매수 검토 알림", enabled: true, severity: "warning" },
  { id: "alert-hynix-12", symbol: "000660", name: "SK하이닉스", ruleType: "3개월 고점 대비 하락률", thresholdValue: -12, actionMessage: "2차 매수 또는 하락전환 점검", enabled: true, severity: "warning" },
  { id: "alert-hynix-15", symbol: "000660", name: "SK하이닉스", ruleType: "3개월 고점 대비 하락률", thresholdValue: -15, actionMessage: "추가매수 금지 / 하락전환 위험", enabled: true, severity: "danger" },
  { id: "alert-samsung-8", symbol: "005930", name: "삼성전자", ruleType: "3개월 고점 대비 하락률", thresholdValue: -8, actionMessage: "1차 매수 검토 알림", enabled: true, severity: "warning" },
  { id: "alert-chip-weight-55", symbol: "SEMICONDUCTOR", name: "반도체 총 비중", ruleType: "비중 초과", thresholdValue: 55, actionMessage: "반도체 비중 주의", enabled: true, severity: "warning" },
  { id: "alert-chip-weight-60", symbol: "SEMICONDUCTOR", name: "반도체 총 비중", ruleType: "비중 초과", thresholdValue: 60, actionMessage: "반도체 추가매수 금지", enabled: true, severity: "danger" },
  { id: "alert-cash-target", symbol: "CASH", name: "전체 현금", ruleType: "방어현금 목표 미만", thresholdValue: 0, actionMessage: "방어자금 훼손 경고", enabled: true, severity: "danger" },
  { id: "alert-sp500-day", symbol: "360750", name: "TIGER 미국S&P500", ruleType: "일간 하락률", thresholdValue: -2, actionMessage: "분할매수 후보 알림", enabled: true, severity: "info" },
  { id: "alert-nasdaq-day", symbol: "133690", name: "TIGER 미국나스닥100", ruleType: "일간 하락률", thresholdValue: -3, actionMessage: "분할매수 후보 알림", enabled: true, severity: "info" },
];
